apiVersion: v1
kind: Service
metadata:
  name: {{ include "openspeedtest.fullname" . }}
  labels:
    {{- include "openspeedtest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "LoadBalancer" }}
{{- if hasKey .Values.service "loadBalancerIP" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP}}
{{- end }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openspeedtest.selectorLabels" . | nindent 4 }}
